### ISSUE TITLE
Unique Identifier used in deces API

### ISSUE THREAD

**Issue by keccak-256** [matchID-project/uptime#286]
I want to ask about the API that uses a unique identifier to fetch a record **https://deces.matchid.io/deces/api/v1/id/**, so this "id" field is attached to the user after death or before?
@cristianpb @rhanka

**Comment by cristianpb** [comment]
The *id* is a unique identifier for each identity on the database. 
It's a base64 representation of the characteristics of the identity (first name, last name, birth date, birth location, death date and death location).
The details can be found here: https://github.com/matchID-project/deces-dataprep/blob/dev/projects/deces-dataprep/recipes/deces_dataprep.yml#L14

**Comment by keccak-256** [comment]
> The _id_ is a unique identifier for each identity on the database. It's a base64 representation of the characteristics of the identity (first name, last name, birth date, birth location, death date and death location). The details can be found here: https://github.com/matchID-project/deces-dataprep/blob/dev/projects/deces-dataprep/recipes/deces_dataprep.yml#L14


Is there any other way to uniquely identify a dead person by providing details?

I am trying to create an exact base64 char from the above details  in typescript, but my implementation consoles different result
Here is my implementation
```
import { Blake3Hasher } from "@napi-rs/blake-hash";

const first_name = "Elijah";
const last_name = "Julien";
const birth_date = "19271223";
const birth_location = "75113";
const death_date = "20230216";
const death_location = "10298";

const tuple = [
  first_name,
  last_name,
  birth_date,
  birth_location,
  death_date,
  death_location,
];

const tupleStr = tuple.join(" ");
console.log("🚀 ~ file: index.ts:22 ~ tupleStr:", tupleStr);

const encoder = new TextEncoder();
const utf8Bytes = encoder.encode(tupleStr);
// console.log("🚀 ~ file: index.ts:26 ~ utf8Bytes:", utf8Bytes)

const hasher = new Blake3Hasher();
hasher.update(Buffer.from(utf8Bytes));
const hash = hasher.digest();
console.log("🚀 ~ file: index.ts:32 ~ hash:", hash);

const base64_encodedString = btoa(hash);
console.log(
  "🚀 ~ file: index.ts:35 ~ base64_encodedString:",
  base64_encodedString.slice(0, 12)
);

//ywgeDVFk5_BC --- expected
//NjRiNWZmMWRk --- retrieved

// (base64.urlsafe_b64encode(blake3(str(tuple(row)).encode('utf-8')).digest()), axis=1).str.slice(stop=12)
```

**Comment by keccak-256** [comment]
@cristianpb can you please guide how to reproduce exact same base64 identifier or code snippet in any language 
Also, it would be helpful if you point out where are the test cases written to generate identifiers, so I can check in which format `tuple` is being passed as an argument
Thanks!

**Comment by cristianpb** [comment]
@keccak-256 
Here you can find a code snippet in python to calculate the ID

https://replit.com/@cristianpb/DecesDataPrepID?v=1

I will be interesting if you are able to reproduce the same process in JS

**Comment by keccak-256** [comment]
> @keccak-256 Here you can find a code snippet in python to calculate the ID
> 
> https://replit.com/@cristianpb/DecesDataPrepID?v=1
> 
> I will be interesting if you are able to reproduce the same process in JS

Thanks for sharing the code snippet 
I'll try to reproduce in JS, and get back to you if need some help.
